home_button = '//*[@id="HEADER_CONTAINER"]/div[2]/nav/div/button[1]'
tv_guide = '//*[@id="HEADER_CONTAINER"]/div[2]/nav/div/button[2]'
settings_button = '//*[@id="HEADER_CONTAINER"]/div[2]/nav/div/button[3]'
guide_choice ='//*[@id="root"]/div/div/div[1]/div[2]/div/div/div[2]/div/div/div[3]/button[1]/div[1]/span[2]'
modern_guide = '//*[@id="root"]/div/div/div[1]/div[2]/div/div/div[2]/div/div/div[3]/button[1]'
##watch_now_button ='//*[@class="sc-cxFLnm cLCMyK"]'
watch_now_button='//*[@id="root"]/div[2]/div/div[2]/div/div[2]/div/button'
up_arrow = '//*[@id="dish-bitmovin-player"]/div[5]/div/div[1]/img'
down_arrow = '//*[@id="dish-bitmovin-player"]/div[5]/div/div[3]/img'
right_arrow = '//*[@id="dish-bitmovin-player"]/div[5]/div/div[4]/img'
left_arrow = '//*[@id="dish-bitmovin-player"]/div[5]/div/div[1]/img'
play_live_tvguide = '//*[@id="WATCH_NOW_BUTTON"]/img'
close_live_video= '//*[@id="PLAYER_CLOSE_BTN"]/img'
classic_guide=  '//*[@id="root"]/div/div/div[1]/div[2]/div/div/div[2]/div/div/div[3]/button[2]'
right_arrow_classic = '//*[@id="root"]/div/div/div[1]/div[2]/div/div/div/div/div/div[1]/div/div[1]/div[2]/div/img'
left_arrow_classic = '//*[@id="root"]/div/div/div[1]/div[2]/div/div/div/div/div/div[1]/div/div[1]/div[4]/div/img'
